import React, { useState,useContext } from 'react';
import './LandingPage.css';
import { Link } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import { UserContext } from '../context/Usercontext';


const LandingPage = () => {
  const [activeFeature, setActiveFeature] = useState(0);
  const { user } = useContext(UserContext); // FIX: useContext instead of calling UserContext directly
  const navigate = useNavigate(); // ADD

  const [openAuthModal, setOpenAuthModal] = useState(false); // ADD
  const [currentPage, setCurrentPage] = useState("login"); // ADD

  const handleCTA = () => { // ADD
    if (!user) {
      setOpenAuthModal(true);
    } else {
      navigate("/dashboard");
    }
  };

  const features = [
    {
      title: "Tailored Just for You",
      description: "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here.",
      icon: "🎯",
      color: "blue"
    },
    {
      title: "Learn at Your Own Pace", 
      description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
      icon: "📚",
      color: "green"
    },
    {
      title: "Capture Your Insights",
      description: "Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful.",
      icon: "🧠",
      color: "purple"
    },
    {
      title: "Understand the 'Why' Behind Answers",
      description: "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
      icon: "⚡",
      color: "orange"
    },
    {
      title: "Save, Organize, and Revisit",
      description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
      icon: "🛡️",
      color: "red"
    }
  ];

  const questions = [
    "What is JSX? Explain its role in React.",
    "What is React.js and what are its main advantages?",
    "Explain the difference between 'props' and 'state' in React.",
    "How does the virtual DOM work in React and why is it important?",
    "Describe the lifecycle methods of a React component."
  ];

  return (
    <div className="landing-page">
      {/* Navigation */}
      <nav className="navbar">
        <div className="logo">
          <div className="logo-icon">AI</div>
          <span className="logo-text">Interview Prep AI</span>
        </div>
        
        <div className="nav-links">
          <a href="#features">Features</a>
          <a href="#how-it-works">How It Works</a>
          <a href="#pricing">Pricing</a>
          <Link to="/login" className="login-btn">Login / Sign Up</Link>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="hero">
        <div className="hero-grid">
          <div className="hero-content">
            <div className="ai-badge">
              <span>⭐</span>
              AI Powered
            </div>
            
            <h1 className="hero-title">
              Ace Interviews with<br/>
              <span className="highlight">AI-Powered</span> Learning
            </h1>
            
            <p className="hero-description">
              Get role-specific questions, expand answers when you need them, dive deeper into concepts, and organize everything your way. From preparation to mastery — your ultimate interview toolkit is here.
            </p>
            
            <div className="hero-buttons">
              <button className="btn-primary">
                Get Started
                <span>→</span>
              </button>
              <button className="btn-secondary">
                <span>▶</span>
                Watch Demo
              </button>
            </div>
          </div>
          
          {/* Demo Preview */}
          <div className="demo-preview">
            <div className="demo-card">
              <div className="browser-dots">
                <div className="dot red"></div>
                <div className="dot yellow"></div>
                <div className="dot green"></div>
              </div>
              
              <div className="demo-content">
                <div className="role-card">
                  <h3 className="role-title">Frontend Developer</h3>
                  <div className="tech-tags">
                    <span className="tag react">React.js</span>
                    <span className="tag dom">DOM</span>
                    <span className="tag css">CSS Flexbox</span>
                  </div>
                  
                  <div className="qa-section">
                    <h4>Interview Q & A</h4>
                    {questions.slice(0, 3).map((question, index) => (
                      <div key={index} className="question-item">
                        <div className="question-dot"></div>
                        <p className="question-text">{question}</p>
                      </div>
                    ))}
                  </div>
                </div>
                
                <div className="guide-card">
                  <div className="guide-header">
                    <div className="pulse-dot"></div>
                    <span className="guide-title">CSS Flexbox: A Beginner's Guide</span>
                  </div>
                  <p className="guide-text">
                    CSS Flexbox is a powerful layout model in CSS. It's designed to make it easier to design flexible and responsive web page layouts...
                  </p>
                </div>
              </div>
            </div>
            
            {/* Floating elements */}
            <div className="floating-element floating-1"></div>
            <div className="floating-element floating-2"></div>
          </div>
        </div>
      </main>

      {/* Stats Section */}
      <section className="stats">
        <div className="stats-container">
          <div className="stats-grid">
            <div className="stat-item">
              <div className="stat-number">10K+</div>
              <div className="stat-label">Questions Generated</div>
            </div>
            <div className="stat-item">
              <div className="stat-number">95%</div>
              <div className="stat-label">Success Rate</div>
            </div>
            <div className="stat-item">
              <div className="stat-number">50+</div>
              <div className="stat-label">Job Roles Covered</div>
            </div>
            <div className="stat-item">
              <div className="stat-number">2.5K+</div>
              <div className="stat-label">Happy Users</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="features">
        <div className="features-container">
          <div className="features-header">
            <h2 className="features-title">Features That Make You Shine</h2>
            <p className="features-subtitle">
              Everything you need to prepare, practice, and excel in your next interview
            </p>
          </div>
          
          <div className="features-grid">
            {features.map((feature, index) => (
              <div 
                key={index}
                className={`feature-card ${activeFeature === index ? 'active' : ''}`}
                onMouseEnter={() => setActiveFeature(index)}
              >
                <div className={`feature-icon ${feature.color}`}>
                  <span style={{fontSize: '1.5rem'}}>{feature.icon}</span>
                </div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-description">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta">
        <div className="cta-container">
          <h2 className="cta-title">Ready to Ace Your Next Interview?</h2>
          <p className="cta-description">
            Join thousands of successful candidates who used our AI-powered platform to land their dream jobs.
          </p>
          <button className="cta-button">Start Your Free Trial</button>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-container">
          <div className="footer-grid">
            <div className="footer-brand">
              <div className="footer-logo">
                <div className="logo-icon">AI</div>
                <span className="logo-text">Interview Prep AI</span>
              </div>
              <p className="footer-description">
                Your ultimate AI-powered interview preparation platform.
              </p>
            </div>
            
            <div className="footer-section">
              <h4>Product</h4>
              <div className="footer-links">
                <a href="#features">Features</a>
                <a href="#pricing">Pricing</a>
                <a href="#faq">FAQ</a>
              </div>
            </div>
            
            <div className="footer-section">
              <h4>Company</h4>
              <div className="footer-links">
                <a href="#about">About</a>
                <a href="#blog">Blog</a>
                <a href="#contact">Contact</a>
              </div>
            </div>
            
            <div className="footer-section">
              <h4>Support</h4>
              <div className="footer-links">
                <a href="#help">Help Center</a>
                <a href="#privacy">Privacy Policy</a>
                <a href="#terms">Terms of Service</a>
              </div>
            </div>
          </div>
          
          <div className="footer-bottom">
            <p>Made with ❤️ Happy Coding</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
