export const CARD_BG = [
  { id: 1, bgColor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgColor: 'linear-gradient(135deg, #fef9e7 0%, #fff6d4 100%)' },
  { id: 3, bgColor: 'linear-gradient(135deg, #eaf7f8 0%, #dff7f9 100%)' },
  { id: 4, bgColor: 'linear-gradient(135deg, #fff29e 0%, #fff7a6 100%)' },
  { id: 5, bgColor: 'linear-gradient(135deg, #e7f6fe 0%, #e7f6fe 100%)' },
  { id: 6, bgColor: 'linear-gradient(135deg, #f5f6fc 0%, #fbfbff 100%)' },
  { id: 7, bgColor: 'linear-gradient(135deg, #fff4fc 0%, #f8e0f0 100%)' },
  { id: 8, bgColor: 'linear-gradient(135deg, #fef7f3 0%, #fff7f3 100%)' },
  { id: 9, bgColor: 'linear-gradient(135deg, #fef2f2 0%, #fef2f2 100%)' },
  { id: 10, bgColor: 'linear-gradient(135deg, #fef2f2 0%, #fef2f2 100%)' },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and career goals.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top to stay organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Go beyond memorization—unlock detailed concept explanations generated by AI.",
  },
  {
    id: "05",
    title: "Track Your Progress",
    description:
      "Monitor completed sessions, identify weak areas, and focus your preparation effectively.",
  },
  {
    id: "06",
    title: "Real Interview Simulation",
    description:
      "Practice with timed sessions and simulated interview scenarios to boost confidence.",
  },
  {
    id: "07",
    title: "Multi-Role Coverage",
    description:
      "From full-stack development to data analytics—choose your career path and practice accordingly.",
  },
  {
    id: "08",
    title: "AI-Powered Suggestions",
    description:
      "Get instant follow-up questions and personalized study recommendations during practice.",
  },
  {
    id: "09",
    title: "Seamless Cross-Device Access",
    description:
      "Start on your laptop, continue on mobile. Your sessions sync across all devices automatically.",
  },
  {
    id: "10",
    title: "Stay Motivated with Milestones",
    description:
      "Unlock achievements and streaks to stay consistent and make learning engaging.",
  },
];
